---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardano-explorer-api
spec:
  rules:
    - host: explorer-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: cardano-explorer-api
                port:
                  number: 8101
            path: /
            pathType: Prefix
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - explorer-api.mainnet.local
    #secretName: local-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardano-submit-api
spec:
  rules:
    - host: submit-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: cardano-submit-api
                port: 
                  number: 8091
            path: /
            pathType: Prefix
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - submit-api.mainnet.local
    #secretName: local-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardano-graphql-api
spec:
  rules:
    - host: graphql-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: cardano-graphql
                port: 
                  number: 3100
            path: /
            pathType: Prefix

  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - graphql-api.mainnet.local
    #secretName: local-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chisel-api
spec:
  rules:
    - host: chisel-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: chisel-server
                port: 
                  number: 40000
            path: /
            pathType: Prefix

  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - chisel-api.mainnet.local
    #secretName: local-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ogmios-api
spec:
  rules:
    - host: ogmios-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: ogmios
                port: 
                  number: 1337
            path: /
            pathType: Prefix

  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - ogmios-api.mainnet.local
    #secretName: local-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgrest-api
spec:
  rules:
    - host: postgrest-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: postgrest
                port: 
                  number: 3000
            path: /
            pathType: Prefix

  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - postgrest-api.mainnet.local
    #secretName: local-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koios-api
spec:
  rules:
    - host: koios-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: koios-api
                port: 
                  number: 3000
            path: /
            pathType: Prefix

  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - koios-api.mainnet.local
    #secretName: local-tls


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rosetta-api
spec:
  rules:
    - host: rosetta-api.mainnet.local
      http:
        paths:
          - backend:
              service:
                name: cardano-rosetta
                port: 
                  number: 8080
            path: /
            pathType: Prefix

  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - rosetta-api.mainnet.local
    #secretName: local-tls

